
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "../components/SideBar"
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <div className="h-16 bg-gray-900 text-white flex items-center justify-center">
          <NavBar />
        </div>
        <div className="flex">
        <div className="flex flex-1 min-h-screen  max-w-xs">
          <SideBar />
          </div>
          <div className="flex-1 ">{children}</div>
          </div>
      </body>
    </html>
  );
}
